// Code generated by gen/generate.go. DO NOT EDIT.
// make edits in gen/generate.go

// Copyright 2022 The GithubEvents Authors. All rights reserved.
// Use of this source code is governed by the MIT License
// that can be found in the LICENSE file.

package githubevents

import (
	"context"
	"errors"
	"github.com/google/go-github/v75/github"
	"sync"
	"testing"
)

func TestOnMarketplacePurchaseEventAny(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventAny(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventAnyAction]) == 0 {
				t.Errorf("failed to add callbacks, got %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventAnyAction]))
			}
		})
	}
}

func TestSetOnMarketplacePurchaseEventAny(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 1,
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			// add callbacks to be overwritten
			g.SetOnMarketplacePurchaseEventAny(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				return nil
			})
			g.SetOnMarketplacePurchaseEventAny(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventAnyAction]) != tt.want {
				t.Errorf("failed to add callbacks, got %d, want %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventAnyAction]), tt.want)
			}
		})
	}
}

func TestHandleMarketplacePurchaseEventAny(t *testing.T) {

	action := "*"

	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
		fail       bool
		panic      bool
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "must pass",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",

				event: &github.MarketplacePurchaseEvent{Action: &action},

				fail: false,
			},
			wantErr: false,
		},
		{
			name: "must fail with error",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",

				event: &github.MarketplacePurchaseEvent{Action: &action},

				fail: true,
			},
			wantErr: true,
		},
		{
			name: "must fail with error on panic recover",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",

				event: &github.MarketplacePurchaseEvent{Action: &action},

				fail:  false,
				panic: true,
			},
			wantErr: true,
		},
		{
			name: "must fail event nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      nil,
				fail:       false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventAny(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				if tt.args.fail {
					return errors.New("fake error")
				}
				if tt.args.panic {
					panic("fake panic")
				}
				return nil
			})
			if err := g.handleMarketplacePurchaseEventAny(context.Background(), tt.args.deliveryID, tt.args.deliveryID, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("TestHandleMarketplacePurchaseEventAny() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestOnMarketplacePurchaseEventPurchased(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventPurchased(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPurchasedAction]) == 0 {
				t.Errorf("failed to add callbacks, got %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPurchasedAction]))
			}
		})
	}
}

func TestSetOnMarketplacePurchaseEventPurchased(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 1,
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			// add callbacks to be overwritten
			g.SetOnMarketplacePurchaseEventPurchased(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				return nil
			})
			g.SetOnMarketplacePurchaseEventPurchased(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPurchasedAction]) != tt.want {
				t.Errorf("failed to add callbacks, got %d, want %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPurchasedAction]), tt.want)
			}
		})
	}
}

func TestHandleMarketplacePurchaseEventPurchased(t *testing.T) {
	action := MarketplacePurchaseEventPurchasedAction

	emptyAction := ""
	fakeAction := "doesntexist"

	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
		fail       bool
		panic      bool
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "must pass",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
			},
			wantErr: false,
		},
		{
			name: "must fail with error",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       true,
			},
			wantErr: true,
		},
		{
			name: "must fail with error on panic recover",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
				panic:      true,
			},
			wantErr: true,
		},
		{
			name: "must fail event nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      nil,
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail with wrong action",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &fakeAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action empty",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &emptyAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
				fail:       false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventPurchased(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				if tt.args.fail {
					return errors.New("fake error")
				}
				if tt.args.panic {
					panic("fake panic")
				}
				return nil
			})
			if err := g.handleMarketplacePurchaseEventPurchased(context.Background(), tt.args.deliveryID, tt.args.eventName, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("handleMarketplacePurchaseEventPurchased() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestOnMarketplacePurchaseEventPendingChange(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventPendingChange(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeAction]) == 0 {
				t.Errorf("failed to add callbacks, got %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeAction]))
			}
		})
	}
}

func TestSetOnMarketplacePurchaseEventPendingChange(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 1,
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			// add callbacks to be overwritten
			g.SetOnMarketplacePurchaseEventPendingChange(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				return nil
			})
			g.SetOnMarketplacePurchaseEventPendingChange(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeAction]) != tt.want {
				t.Errorf("failed to add callbacks, got %d, want %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeAction]), tt.want)
			}
		})
	}
}

func TestHandleMarketplacePurchaseEventPendingChange(t *testing.T) {
	action := MarketplacePurchaseEventPendingChangeAction

	emptyAction := ""
	fakeAction := "doesntexist"

	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
		fail       bool
		panic      bool
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "must pass",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
			},
			wantErr: false,
		},
		{
			name: "must fail with error",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       true,
			},
			wantErr: true,
		},
		{
			name: "must fail with error on panic recover",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
				panic:      true,
			},
			wantErr: true,
		},
		{
			name: "must fail event nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      nil,
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail with wrong action",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &fakeAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action empty",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &emptyAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
				fail:       false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventPendingChange(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				if tt.args.fail {
					return errors.New("fake error")
				}
				if tt.args.panic {
					panic("fake panic")
				}
				return nil
			})
			if err := g.handleMarketplacePurchaseEventPendingChange(context.Background(), tt.args.deliveryID, tt.args.eventName, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("handleMarketplacePurchaseEventPendingChange() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestOnMarketplacePurchaseEventPendingChangeCanceled(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventPendingChangeCanceled(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeCanceledAction]) == 0 {
				t.Errorf("failed to add callbacks, got %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeCanceledAction]))
			}
		})
	}
}

func TestSetOnMarketplacePurchaseEventPendingChangeCanceled(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 1,
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			// add callbacks to be overwritten
			g.SetOnMarketplacePurchaseEventPendingChangeCanceled(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				return nil
			})
			g.SetOnMarketplacePurchaseEventPendingChangeCanceled(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeCanceledAction]) != tt.want {
				t.Errorf("failed to add callbacks, got %d, want %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventPendingChangeCanceledAction]), tt.want)
			}
		})
	}
}

func TestHandleMarketplacePurchaseEventPendingChangeCanceled(t *testing.T) {
	action := MarketplacePurchaseEventPendingChangeCanceledAction

	emptyAction := ""
	fakeAction := "doesntexist"

	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
		fail       bool
		panic      bool
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "must pass",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
			},
			wantErr: false,
		},
		{
			name: "must fail with error",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       true,
			},
			wantErr: true,
		},
		{
			name: "must fail with error on panic recover",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
				panic:      true,
			},
			wantErr: true,
		},
		{
			name: "must fail event nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      nil,
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail with wrong action",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &fakeAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action empty",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &emptyAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
				fail:       false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventPendingChangeCanceled(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				if tt.args.fail {
					return errors.New("fake error")
				}
				if tt.args.panic {
					panic("fake panic")
				}
				return nil
			})
			if err := g.handleMarketplacePurchaseEventPendingChangeCanceled(context.Background(), tt.args.deliveryID, tt.args.eventName, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("handleMarketplacePurchaseEventPendingChangeCanceled() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestOnMarketplacePurchaseEventChanged(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventChanged(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventChangedAction]) == 0 {
				t.Errorf("failed to add callbacks, got %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventChangedAction]))
			}
		})
	}
}

func TestSetOnMarketplacePurchaseEventChanged(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 1,
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			// add callbacks to be overwritten
			g.SetOnMarketplacePurchaseEventChanged(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				return nil
			})
			g.SetOnMarketplacePurchaseEventChanged(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventChangedAction]) != tt.want {
				t.Errorf("failed to add callbacks, got %d, want %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventChangedAction]), tt.want)
			}
		})
	}
}

func TestHandleMarketplacePurchaseEventChanged(t *testing.T) {
	action := MarketplacePurchaseEventChangedAction

	emptyAction := ""
	fakeAction := "doesntexist"

	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
		fail       bool
		panic      bool
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "must pass",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
			},
			wantErr: false,
		},
		{
			name: "must fail with error",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       true,
			},
			wantErr: true,
		},
		{
			name: "must fail with error on panic recover",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
				panic:      true,
			},
			wantErr: true,
		},
		{
			name: "must fail event nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      nil,
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail with wrong action",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &fakeAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action empty",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &emptyAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
				fail:       false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventChanged(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				if tt.args.fail {
					return errors.New("fake error")
				}
				if tt.args.panic {
					panic("fake panic")
				}
				return nil
			})
			if err := g.handleMarketplacePurchaseEventChanged(context.Background(), tt.args.deliveryID, tt.args.eventName, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("handleMarketplacePurchaseEventChanged() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestOnMarketplacePurchaseEventCanceled(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFunc",
			args: args{
				callbacks: []MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventCanceled(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventCanceledAction]) == 0 {
				t.Errorf("failed to add callbacks, got %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventCanceledAction]))
			}
		})
	}
}

func TestSetOnMarketplacePurchaseEventCanceled(t *testing.T) {
	type args struct {
		callbacks []MarketplacePurchaseEventHandleFunc
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "must add single MarketplacePurchaseEventHandleFunc",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 1,
		},
		{
			name: "must add multiple MarketplacePurchaseEventHandleFuncs",
			args: args{
				[]MarketplacePurchaseEventHandleFunc{
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
					func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
						return nil
					},
				},
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			// add callbacks to be overwritten
			g.SetOnMarketplacePurchaseEventCanceled(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				return nil
			})
			g.SetOnMarketplacePurchaseEventCanceled(tt.args.callbacks...)
			if len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventCanceledAction]) != tt.want {
				t.Errorf("failed to add callbacks, got %d, want %d", len(g.onMarketplacePurchaseEvent[MarketplacePurchaseEventCanceledAction]), tt.want)
			}
		})
	}
}

func TestHandleMarketplacePurchaseEventCanceled(t *testing.T) {
	action := MarketplacePurchaseEventCanceledAction

	emptyAction := ""
	fakeAction := "doesntexist"

	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
		fail       bool
		panic      bool
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "must pass",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
			},
			wantErr: false,
		},
		{
			name: "must fail with error",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       true,
			},
			wantErr: true,
		},
		{
			name: "must fail with error on panic recover",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &action},
				fail:       false,
				panic:      true,
			},
			wantErr: true,
		},
		{
			name: "must fail event nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      nil,
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail with wrong action",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &fakeAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action empty",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: &emptyAction},
				fail:       false,
			},
			wantErr: true,
		},
		{
			name: "must fail event action nil",
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
				fail:       false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New("fake")
			g.OnMarketplacePurchaseEventCanceled(func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
				if tt.args.fail {
					return errors.New("fake error")
				}
				if tt.args.panic {
					panic("fake panic")
				}
				return nil
			})
			if err := g.handleMarketplacePurchaseEventCanceled(context.Background(), tt.args.deliveryID, tt.args.eventName, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("handleMarketplacePurchaseEventCanceled() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestMarketplacePurchaseEvent(t *testing.T) {
	type fields struct {
		handler *EventHandler
	}
	type args struct {
		deliveryID string
		eventName  string
		event      *github.MarketplacePurchaseEvent
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
	}{
		{
			name: "must trigger MarketplacePurchaseEventAny with unknown event action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  MarketplacePurchaseEvent,

				event: &github.MarketplacePurchaseEvent{Action: ptrString("unknown")},
			},
			wantErr: false,
		},

		{
			name: "must trigger MarketplacePurchaseEventPurchased",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPurchasedAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPurchasedAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString(MarketplacePurchaseEventPurchasedAction)},
			},
			wantErr: false,
		},
		{
			name: "must fail MarketplacePurchaseEventPurchased with empty action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPurchasedAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPurchasedAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString("")},
			},
			wantErr: true,
		},
		{
			name: "must fail MarketplacePurchaseEventPurchased with nil action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPurchasedAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPurchasedAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
			},
			wantErr: true,
		},

		{
			name: "must trigger MarketplacePurchaseEventPendingChange",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPendingChangeAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPendingChangeAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString(MarketplacePurchaseEventPendingChangeAction)},
			},
			wantErr: false,
		},
		{
			name: "must fail MarketplacePurchaseEventPendingChange with empty action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPendingChangeAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPendingChangeAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString("")},
			},
			wantErr: true,
		},
		{
			name: "must fail MarketplacePurchaseEventPendingChange with nil action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPendingChangeAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPendingChangeAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
			},
			wantErr: true,
		},

		{
			name: "must trigger MarketplacePurchaseEventPendingChangeCanceled",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPendingChangeCanceledAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPendingChangeCanceledAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString(MarketplacePurchaseEventPendingChangeCanceledAction)},
			},
			wantErr: false,
		},
		{
			name: "must fail MarketplacePurchaseEventPendingChangeCanceled with empty action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPendingChangeCanceledAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPendingChangeCanceledAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString("")},
			},
			wantErr: true,
		},
		{
			name: "must fail MarketplacePurchaseEventPendingChangeCanceled with nil action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventPendingChangeCanceledAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventPendingChangeCanceledAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
			},
			wantErr: true,
		},

		{
			name: "must trigger MarketplacePurchaseEventChanged",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventChangedAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventChangedAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString(MarketplacePurchaseEventChangedAction)},
			},
			wantErr: false,
		},
		{
			name: "must fail MarketplacePurchaseEventChanged with empty action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventChangedAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventChangedAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString("")},
			},
			wantErr: true,
		},
		{
			name: "must fail MarketplacePurchaseEventChanged with nil action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventChangedAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventChangedAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
			},
			wantErr: true,
		},

		{
			name: "must trigger MarketplacePurchaseEventCanceled",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventCanceledAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventCanceledAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString(MarketplacePurchaseEventCanceledAction)},
			},
			wantErr: false,
		},
		{
			name: "must fail MarketplacePurchaseEventCanceled with empty action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventCanceledAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventCanceledAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: ptrString("")},
			},
			wantErr: true,
		},
		{
			name: "must fail MarketplacePurchaseEventCanceled with nil action",
			fields: fields{
				handler: &EventHandler{
					WebhookSecret: "fake",
					onBeforeAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onBeforeAny called")
								return nil
							},
						},
					},
					onAfterAny: map[string][]EventHandleFunc{
						EventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event any) error {
								t.Log("onAfterAny called")
								return nil
							},
						},
					},
					onMarketplacePurchaseEvent: map[string][]MarketplacePurchaseEventHandleFunc{
						MarketplacePurchaseEventAnyAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Log("onAny action called")
								return nil
							},
						},
						MarketplacePurchaseEventCanceledAction: {
							func(ctx context.Context, deliveryID string, eventName string, event *github.MarketplacePurchaseEvent) error {
								t.Logf("%s action called", MarketplacePurchaseEventCanceledAction)
								return nil
							},
						},
					},
				},
			},
			args: args{
				deliveryID: "42",
				eventName:  "marketplace_purchase",
				event:      &github.MarketplacePurchaseEvent{Action: nil},
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := &EventHandler{
				WebhookSecret: "fake",
				mu:            sync.RWMutex{},
			}
			if err := g.MarketplacePurchaseEvent(context.Background(), tt.args.deliveryID, tt.args.eventName, tt.args.event); (err != nil) != tt.wantErr {
				t.Errorf("MarketplacePurchaseEvent() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
